### ISSUE TITLE
Refactoring: package managers: pip: tracker

### ISSUE THREAD

**Issue by eskultety** [containerbuildsystem/cachi2#484]
### This is the main refactoring tracker for the pip package manager module.
The list will be updated as necessary.

- [ ] Convert `PipRequirement._assess_direct_access_requirement` to a static helper method instead of a class method
- [ ] Convert `PipRequirement._split_hashes_from_options` to a static helper method instead of a class method
- [ ] Enable typing for `PipRequirement.from_line` class method
- [ ] Make `PipRequirement` a subclass of `packaging.Requirement`
- [ ] Break the module's functionality into several logical modules contained in a subpackage (see the Yarn subpackage and modules for inspiration)
